modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/issues"

[[mods]]
modId="modcienciamagia"
version="1.0.0"
displayName="Ciencia e Magia"
authors="Jules"
description='''
Um mod que transforma o Minecraft com ciência, tecnologia, magia e alquimia.
'''

[[dependencies.modcienciamagia]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.modcienciamagia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.modcienciamagia]]
    modId="kubejs"
    mandatory=true
    versionRange="[2001.6.4-build.114,)"
    ordering="NONE"
    side="BOTH"